/**
 * DPC-API
 * Die ist die REST-artige Schnittstelle, für das DPC-Projekt.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FrameValueAttribute } from './frameValueAttribute';
import { InsulinPumpProfileConfig } from './insulinPumpProfileConfig';
import { InsulinConfig } from './insulinConfig';
import { KEFactors } from './kEFactors';
import { CorrectionsFactors } from './correctionsFactors';


export interface ContextUpdateRequestContextUpdate { 
    frameValues?: FrameValueAttribute;
    keFactors?: KEFactors;
    correctionsFactors?: CorrectionsFactors;
    insulinConfig?: InsulinConfig;
    insulinPumpPofileConfig?: InsulinPumpProfileConfig;
}

