/**
 * Diabetes Web-App
 * Die ist die vorläufige REST-artige Schnittstelle, für das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialität benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryReprAcitvity } from './entryReprAcitvity';
import { EntryReprResponseCorrectionBolus } from './entryReprResponseCorrectionBolus';
import { EntryReprResponseMealBolus } from './entryReprResponseMealBolus';
import { EntryReprResponseMedication } from './entryReprResponseMedication';
import { EntryReprResponseTags } from './entryReprResponseTags';
import { EntryReprTempBasalChange } from './entryReprTempBasalChange';


export interface EntryReprResponse { 
    /**
     * Die ID des Eintrages
     */
    selfID?: string;
    /**
     * Unix-Zeit
     */
    timeStamp: number;
    /**
     * Blutzucker in mmol/l
     */
    bloodSugar?: number;
    mealBolus?: EntryReprResponseMealBolus;
    correctionBolus?: EntryReprResponseCorrectionBolus;
    basal?: EntryReprResponseMealBolus;
    /**
     * Eingenommene KH in Austauscheinheiten
     */
    mealUnits?: number;
    mealDescription?: string;
    comment?: string;
    tempBasalChange?: EntryReprTempBasalChange;
    medication?: EntryReprResponseMedication;
    acitvity?: EntryReprAcitvity;
    /**
     * Die IDs der Tags
     */
    tags?: Array<EntryReprResponseTags>;
}

