/**
 * Diabetes Web-App
 * Die ist die vorl�ufige REST-artige Schnittstelle, f�r das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialit�t benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntryReprAcitvity { 
    duration?: string;
    description?: string;
    strain?: EntryReprAcitvity.StrainEnum;
}
export namespace EntryReprAcitvity {
    export type StrainEnum = -2 | -1 | 0 | 1 | 2;
    export const StrainEnum = {
        NUMBER_MINUS_2: -2 as StrainEnum,
        NUMBER_MINUS_1: -1 as StrainEnum,
        NUMBER_0: 0 as StrainEnum,
        NUMBER_1: 1 as StrainEnum,
        NUMBER_2: 2 as StrainEnum
    };
}

