/**
 * DPC-API
 * Die ist die REST-artige Schnittstelle, für das DPC-Projekt.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryReprAcitvity } from './entryReprAcitvity';
import { EntryReprResponseMedication } from './entryReprResponseMedication';
import { FoodIntake } from './foodIntake';
import { IntervallInsulinIntakeAttr } from './intervallInsulinIntake';
import { EntryReprResponseTags } from './entryReprResponseTags';
import { TimeStampInsulinIntake } from './timeStampInsulinIntake';
import { EntryReprTempBasalChange } from './entryReprTempBasalChange';


export interface EntryReprResponse { 
    /**
     * Die ID des Eintrages
     */
    id?: string;
    /**
     * Unix-Zeit
     */
    timeStamp: number;
    /**
     * Blutzucker in mmol/l
     */
    bloodSugar?: number;
    insulinIntakes?: Array<TimeStampInsulinIntake | IntervallInsulinIntakeAttr>;
    foodIntakes?: Array<FoodIntake>;
    comment?: string;
    tempBasalChange?: EntryReprTempBasalChange;
    medication?: EntryReprResponseMedication;
    acitvity?: EntryReprAcitvity;
    /**
     * Die IDs der Tags
     */
    tags?: Array<EntryReprResponseTags>;
}

