/**
 * DPC-API
 * Die ist die REST-artige Schnittstelle, für das DPC-Projekt.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryReprAcitvity } from './entryReprAcitvity';
import { EntryReprMedication } from './entryReprMedication';
import { EntryReprTempBasalChange } from './entryReprTempBasalChange';
import { EntryReprMealBolus } from './entryReprMealBolus';


export interface EntryRepr { 
    /**
     * Unix-Zeit
     */
    timeStamp: number;
    /**
     * Blutzucker in mmol/l
     */
    bloodSugar?: number;
    mealBolus?: EntryReprMealBolus;
    correctionBolus?: EntryReprMealBolus;
    basal?: EntryReprMealBolus;
    /**
     * Eingenommene KH in Austauscheinheiten
     */
    mealUnits?: number;
    mealDescription?: string;
    comment?: string;
    tempBasalChange?: EntryReprTempBasalChange;
    medication?: EntryReprMedication;
    acitvity?: EntryReprAcitvity;
    /**
     * Die IDs der Tags
     */
    tags?: Array<string>;
}

