/**
 * Diabetes Web-App
 * Die ist die vorläufige REST-artige Schnittstelle, für das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialität benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntryReprTempBasalChange { 
    /**
     * Die Zeit in der die Basalrate der Pumpe geändert werden soll in Sekunden
     */
    duration?: number;
    /**
     * Die Prozent, um wie viel die Rate geändert werden soll.
     */
    percentage?: number;
}

