/**
 * DPC-API
 * Die ist die REST-artige Schnittstelle, für das DPC-Projekt.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntryReprMealBolus { 
    /**
     * Abgabe in IE
     */
    units?: number;
    /**
     * Die ID des Insulins
     */
    insulin?: string;
}

