/**
 * Diabetes Web-App
 * Die ist die vorl�ufige REST-artige Schnittstelle, f�r das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialit�t benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryReprAcitvity } from './entryReprAcitvity';
import { EntryReprMealBolus } from './entryReprMealBolus';
import { EntryReprMedication } from './entryReprMedication';
import { EntryReprTempBasalChange } from './entryReprTempBasalChange';


export interface EntryRepr { 
    /**
     * Unix-Zeit
     */
    timeStamp: number;
    /**
     * Blutzucker in mmol/l
     */
    bloodSugar?: number;
    mealBolus?: EntryReprMealBolus;
    correctionBolus?: EntryReprMealBolus;
    basal?: EntryReprMealBolus;
    /**
     * Eingenommene KH in Austauscheinheiten
     */
    mealUnits?: number;
    mealDescription?: string;
    comment?: string;
    tempBasalChange?: EntryReprTempBasalChange;
    medication?: EntryReprMedication;
    acitvity?: EntryReprAcitvity;
    /**
     * Die IDs der Tags
     */
    tags?: Array<string>;
}

