/**
 * Diabetes Web-App
 * Die ist die vorläufige REST-artige Schnittstelle, für das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialität benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FoodDescr { 
    id?: string;
    resorption?: FoodDescr.ResorptionEnum;
    carbsFactor?: number;
    comment?: string;
}
export namespace FoodDescr {
    export type ResorptionEnum = 'fast' | 'medium' | 'slow';
    export const ResorptionEnum = {
        Fast: 'fast' as ResorptionEnum,
        Medium: 'medium' as ResorptionEnum,
        Slow: 'slow' as ResorptionEnum
    };
}


