/**
 * DPC-API
 * Die ist die REST-artige Schnittstelle, für das DPC-Projekt.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FulldiaryDrugs } from './fulldiaryDrugs';
import { FulldiaryOwner } from './fulldiaryOwner';
import { FoodDescr } from './foodDescr';
import { DiaryPreferences } from './diaryPreferences';


export interface FullDiary { 
    id?: string;
    preferences?: DiaryPreferences;
    owner?: FulldiaryOwner;
    food?: Array<FoodDescr>;
    drugs?: Array<FulldiaryDrugs>;
    insulins?: Array<FulldiaryDrugs>;
    tags?: Array<FulldiaryDrugs>;
}

