/**
 * Diabetes Web-App
 * Die ist die vorl�ufige REST-artige Schnittstelle, f�r das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialit�t benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FulldiaryDrugs } from './fulldiaryDrugs';
import { FulldiaryOwner } from './fulldiaryOwner';


export interface FullDiary { 
    selfId: string;
    owner: FulldiaryOwner;
    name: string;
    patient: string;
    drugs: Array<FulldiaryDrugs>;
    insulins: Array<FulldiaryDrugs>;
    tags: Array<FulldiaryDrugs>;
}

