/**
 * Diabetes Web-App
 * Die ist die vorläufige REST-artige Schnittstelle, für das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialität benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FulldiaryDrugs { 
    name?: string;
    id?: string;
    /**
     * Noch nicht ganz klar, ob diese Werte gelöscht werden dürfen, da Einträge ja mit ID darauf verweisen. Entweder werden Id-Referenzen dann auf null gesetzt, oder dieser Wert als inaktiv makiert.
     */
    active?: boolean;
}

