/**
 * Diabetes Web-App
 * Die ist die vorläufige REST-artige Schnittstelle, für das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialität benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FulldiaryDrugs } from './fulldiaryDrugs';
import { FulldiaryOwner } from './fulldiaryOwner';
import { FoodDescr } from './foodDescr';


export interface FullDiary { 
    id?: string;
    owner?: FulldiaryOwner;
    food?: Array<FoodDescr>;
    drugs?: Array<FulldiaryDrugs>;
    insulins?: Array<FulldiaryDrugs>;
    tags?: Array<FulldiaryDrugs>;
}

