export * from './diaries.service';
import { DiariesService } from './diaries.service';
export * from './eintrge.service';
import { EintrgeService } from './eintrge.service';
export * from './grantManagement.service';
import { GrantManagementService } from './grantManagement.service';
export * from './kontexte.service';
import { KontexteService } from './kontexte.service';
export * from './tagebcherEssensdatenbank.service';
import { TagebcherEssensdatenbankService } from './tagebcherEssensdatenbank.service';
export * from './tagebcherTags.service';
import { TagebcherTagsService } from './tagebcherTags.service';
export * from './userManagement.service';
import { UserManagementService } from './userManagement.service';
export * from './util.service';
import { UtilService } from './util.service';
export const APIS = [DiariesService, EintrgeService, GrantManagementService, KontexteService, TagebcherEssensdatenbankService, TagebcherTagsService, UserManagementService, UtilService];
