/**
 * Diabetes Web-App
 * Die ist die vorl�ufige REST-artige Schnittstelle, f�r das Dia-PC Projekt. Diese Schnittstelle ist nicht REST, da sie nicht Hypermedialit�t benutzt - Das bedeutet, der Client muss selbt Anfragen konstruieren. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { EntryRepr } from '../model/entryRepr';
import { EntryReprResponse } from '../model/entryReprResponse';
import { InlineResponse2002 } from '../model/inlineResponse2002';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class EintrgeService {

    protected basePath = 'https://dia-pc.flexus.click/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Erstelle einen neuen Eintrag in dem Tagebuch.
     * Generell muss nur ein Zeitstempel angegeben werden und die anderen Attribute sind optional. Das bedeutet, dass z.B. bei einer BZ-Messung nur der Zeitstempel und Blutzcker-Wert �bergeben werden muss. Der Aufrufer dieser Methode muss selbst darauf achten, dass die richtigen Medikamenten und Insulin-IDs �bertragen werden. Falsche IDs f�hren zu einem Fehler.
     * @param diaryId Die ID des Tagebuches, bei welchem ein Eintrag hinzugef�gt werden soll.
     * @param entryRepr Eine Repr�sentation des zu erstellenden Tagebuch-Eintrages
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addDiaryEntry(diaryId: string, entryRepr?: EntryRepr, observe?: 'body', reportProgress?: boolean): Observable<EntryReprResponse>;
    public addDiaryEntry(diaryId: string, entryRepr?: EntryRepr, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EntryReprResponse>>;
    public addDiaryEntry(diaryId: string, entryRepr?: EntryRepr, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EntryReprResponse>>;
    public addDiaryEntry(diaryId: string, entryRepr?: EntryRepr, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (diaryId === null || diaryId === undefined) {
            throw new Error('Required parameter diaryId was null or undefined when calling addDiaryEntry.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<EntryReprResponse>(`${this.configuration.basePath}/diaries/${encodeURIComponent(String(diaryId))}/entries`,
            entryRepr,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * L�sche einen Eintrag
     * Hier muss nochmal �berlegt werden, ob und wie Eintr�ge gel�scht werden. Ein anderer Ansatz w�re, dass Eintr�ge ein active Flag haben, dass bei einem Patch gesetzt wird - Das bei einem Delete auszuf�hren w�re vermutlich laut Rest falsch.
     * @param diaryId Die Id des Tagebuches.
     * @param entryId ID des Eintrages
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteDiaryEntry(diaryId: string, entryId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteDiaryEntry(diaryId: string, entryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteDiaryEntry(diaryId: string, entryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteDiaryEntry(diaryId: string, entryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (diaryId === null || diaryId === undefined) {
            throw new Error('Required parameter diaryId was null or undefined when calling deleteDiaryEntry.');
        }
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling deleteDiaryEntry.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/diaries/${encodeURIComponent(String(diaryId))}/entries/${encodeURIComponent(String(entryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Erhalte alle Entries. Optional sollten Such-Kriterien oder Filter angegeben werden k�nnen.
     * &lt;ul&gt; &lt;li&gt; Allgemeine (einache) Suchparameter, werden in der URL-Quey angegeben. &lt;/li&gt; &lt;li&gt; Komplexe Such-Abfragen werden im Body angegeben. Hier m�sste man dann gucken, wie das umsetzbar ist (vorallem mit Caches) da Bodies in Get-Anfragen un�blich sind. &lt;ul&gt; &lt;li&gt; Es muss auch �berlegt werden, ob eine Filterung nach bestimmten Kriterien �berhaupt Serverseitig passieren soll, oder clientseitig. &lt;/li&gt; &lt;li&gt; Nat�rlich unterst�tzt Swagger keine Bodies in Get anfragen. -&gt; Entweder selbst h�ndisch im Code einf�gen, oder in Post und Get aufteilen (Post Filter-Daten, Kriege Such ID zur�ck, mache Get auf Such-Ressource mit ID. ISt f�r Cachen aber auch nicht gut). &lt;/li&gt; &lt;/ul&gt; &lt;/li&gt; &lt;li&gt; Es muss noch �berpr�ft werden, ob die Entries in dieser Liste nur ein Subset der Informationen enthalten sollen und alle Informationen eines Eintrages erst mit dem Get-Request zu dem spezifischen Entry einsehbar sind. &lt;/li&gt; &lt;/ul&gt;
     * @param diaryId Die Id des Tagebuches.
     * @param from Zeit in Unix-Zeit (Einschlie�lich)
     * @param to Zeit in Unix-Zeit (Einschlie�lich)
     * @param limit Die Anzahl der maximalen Eintr�ge, die zur�ckgegeben werden sollen. Ist nur mit order g�ltig.
     * @param order Ob die Eintr�ge beginnend von dem �ltesten oder neusten Eintrag sortiert zur�ckgegeben werden sollen.
     * @param showDeactivatedEntries Je nachdem, wie das L�schen umgesetzt wird, w�re dieses Parameter evtl. sinnvoll.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDiaryEntries(diaryId: string, from?: number, to?: number, limit?: number, order?: 'asc' | 'desc', showDeactivatedEntries?: boolean, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse2002>;
    public getDiaryEntries(diaryId: string, from?: number, to?: number, limit?: number, order?: 'asc' | 'desc', showDeactivatedEntries?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse2002>>;
    public getDiaryEntries(diaryId: string, from?: number, to?: number, limit?: number, order?: 'asc' | 'desc', showDeactivatedEntries?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse2002>>;
    public getDiaryEntries(diaryId: string, from?: number, to?: number, limit?: number, order?: 'asc' | 'desc', showDeactivatedEntries?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (diaryId === null || diaryId === undefined) {
            throw new Error('Required parameter diaryId was null or undefined when calling getDiaryEntries.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (from !== undefined && from !== null) {
            queryParameters = queryParameters.set('from', <any>from);
        }
        if (to !== undefined && to !== null) {
            queryParameters = queryParameters.set('to', <any>to);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (order !== undefined && order !== null) {
            queryParameters = queryParameters.set('order', <any>order);
        }
        if (showDeactivatedEntries !== undefined && showDeactivatedEntries !== null) {
            queryParameters = queryParameters.set('showDeactivatedEntries', <any>showDeactivatedEntries);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<InlineResponse2002>(`${this.configuration.basePath}/diaries/${encodeURIComponent(String(diaryId))}/entries`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Erhalte eine Detaillierte Repr�sentation eines Eintrages.
     * Hier sollten alle ausf�hrlichen Informationen gezeigt werden, die es zu einem Eintrag gibt. Eventuell w�re es auch sinnvoll aufzuzeigen oder zu verlinken, wer was gemacht hat [Aber erst sp�ter]. &lt;br&gt; Evtl. ist dieser Endpoint sp�ter auch nur noch n�tzlich, um f�r einen Eintrag eine Historie anzuzeigen. 
     * @param diaryId Die Id des Tagebuches.
     * @param entryId ID des Eintrages
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDiaryEntry(diaryId: string, entryId: string, observe?: 'body', reportProgress?: boolean): Observable<EntryReprResponse>;
    public getDiaryEntry(diaryId: string, entryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EntryReprResponse>>;
    public getDiaryEntry(diaryId: string, entryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EntryReprResponse>>;
    public getDiaryEntry(diaryId: string, entryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (diaryId === null || diaryId === undefined) {
            throw new Error('Required parameter diaryId was null or undefined when calling getDiaryEntry.');
        }
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling getDiaryEntry.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EntryReprResponse>(`${this.configuration.basePath}/diaries/${encodeURIComponent(String(diaryId))}/entries/${encodeURIComponent(String(entryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Aktualisiere einen Eintrag.
     * Hier sollten nat�rlich nur die Felder angegeben werden, die auch aktualisiert werden sollen.
     * @param diaryId Die Id des Tagebuches.
     * @param entryId ID des Eintrages
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDiaryEntry(diaryId: string, entryId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateDiaryEntry(diaryId: string, entryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateDiaryEntry(diaryId: string, entryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateDiaryEntry(diaryId: string, entryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (diaryId === null || diaryId === undefined) {
            throw new Error('Required parameter diaryId was null or undefined when calling updateDiaryEntry.');
        }
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling updateDiaryEntry.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.patch<any>(`${this.configuration.basePath}/diaries/${encodeURIComponent(String(diaryId))}/entries/${encodeURIComponent(String(entryId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
