/**
 * DPC-API
 * Die ist die REST-artige Schnittstelle, für das DPC-Projekt.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class UtilService {

    protected basePath = 'https://dia-pc.flexus.click/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Bekomme einen Bolus-Vorschlag
     * Dieser End-Point muss eigentlich mit einen GET-Verb arbeiten, jedoch wird aus Realisierungsgründen wie z.B. Swagger ein overloaded Post verwendet. &lt;br&gt; 
     * @param diary Die Id des Tagebuches
     * @param _for (Optional) Für welchen Zeitpunkt soll der Vorschlag sein. Als Default Wert wird der jetzige Zeitpunkt genommen.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getBolusCalculatorBolusRecommendation(diary: string, _for?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getBolusCalculatorBolusRecommendation(diary: string, _for?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getBolusCalculatorBolusRecommendation(diary: string, _for?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getBolusCalculatorBolusRecommendation(diary: string, _for?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (diary === null || diary === undefined) {
            throw new Error('Required parameter diary was null or undefined when calling getBolusCalculatorBolusRecommendation.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (diary !== undefined && diary !== null) {
            queryParameters = queryParameters.set('diary', <any>diary);
        }
        if (_for !== undefined && _for !== null) {
            queryParameters = queryParameters.set('for', <any>_for);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.post<any>(`${this.configuration.basePath}/util/bolusCalculator/bolusRecommendation`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
